### ISSUE TITLE
Testing validation on a related property

### ISSUE THREAD

**Issue by philwindsor** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#10]
Hi,

More of a question than issue....

I've just came across your library and was wondering how you test a validation for this scenario

`class Box
{
 int height;
int width
}`

The validator would look something like

`RuleFor(p => p.height).GreaterThan(q => q.width).WithMessage("height must be greater than width")`

Have I missed something or is there not an overload for passing in a property via an expression?

`.AddPropertyValidatorVerifier<GreaterThanValidator>(0)`

**Comment by MichalJankowskii** [comment]
Unfortunately, right now you are not able to test if the message is correct.

There is no overloaded method that would accept error message or message code.
