### ISSUE TITLE
Length(5, 20) TotalLength Invalid

### ISSUE THREAD

**Issue by zouzjidelu** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#11]
Hello, please ask a question about Length validation rules. Total Length input character length is not recognized. How should we use it?

**Comment by zouzjidelu** [comment]
![1](https://user-images.githubusercontent.com/40453487/54732286-f3130680-4bcd-11e9-8413-902fd0dcf349.png)
![2](https://user-images.githubusercontent.com/40453487/54732291-f7d7ba80-4bcd-11e9-9ed1-50dcdeecfe1c.png)

**Comment by MichalJankowskii** [comment]
Hi,

You should open an issue in https://github.com/JeremySkinner/FluentValidation. This Git repository is for a library that is helping with unit test creation to FluentValidation.
