### ISSUE TITLE
Incorrect EnumValidator field name in EnumValidatorVerifier

### ISSUE THREAD

**Issue by TomSavas** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#12]
https://github.com/MichalJankowskii/FluentValidation.Validators.UnitTestExtension/blob/dbdf87ae0c7e15b4c2938bcd0a48961a8a3ae21e/src/FluentValidation.Validators.UnitTestExtension/ValidatorVerifiers/EnumValidatorVerifier.cs#L20

I believe that instead of `enumType` it should be `_enumType` as in [FluentValidations the private field name is `_enumType`.](https://github.com/JeremySkinner/FluentValidation/blob/009e78949208c4f7e4390d001d1d321a393e8599/src/FluentValidation/Validators/EnumValidator.cs#L28) 
Currently I get a `System.NullReferenceException : Object reference not set to an instance of an object.` exception on the aforementioned line. Adding the underscore seems to fix the issue.

**Comment by MichalJankowskii** [comment]
You are right. In the latest version of FluentValidation implementation has been changed. I will fix it the next days.

**Comment by MichalJankowskii** [comment]
Fixed and publisher
