### ISSUE TITLE
How do test using 'Must'

### ISSUE THREAD

**Issue by keerthinathganjam** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#13]
RuleFor(x => x.Postcode).Must(BeAValidPostcode).WithMessage("Please specify a valid postcode");

I could test that it runs the PredicateValidator, but it would be good to check if it uses the correct Func as well (in this case BeAValidPostcode).

something like 
validator.ShouldHaveRules(x => x.External,
              BaseVerifiersSetComposer.Build()
                .AddPropertyValidatorVerifier<PredicateValidator>(validator.BeAValidPostcode)
            .Create());

**Comment by MichalJankowskii** [comment]
How you would like to check that both predicates are the same? BeAValidPostcode - provided in production code and in unit test?

**Comment by infiycloud** [comment]
@keerthinathganjam , can you please add sample code for "Must" Or "PredicateValidator", i am trying to implement same but not get success.
Thanks.
