### ISSUE TITLE
How to UnitTest DependentRules

### ISSUE THREAD

**Issue by jaumemilian** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#16]
Hi,

We are using this unit test extension in order to validate if the rules are configured:

`_validator.ShouldHaveRules(x => x.IdentityId,
                BaseVerifiersSetComposer.Build()
                    .AddPropertyValidatorVerifier<NotNullValidator>()
                    .AddPropertyValidatorVerifier<NotEmptyValidator>()
                    .Create());`

Is it possible to validate in a similar way when we have DependentRules configured?
I've been not able to solve that

Thanks,
Jaume

**Comment by infiycloud** [comment]
@jaumemilian @MichalJankowskii , I am also looking for same, can you please provide and guidance for same.

**Comment by jaumemilian** [comment]
I haven't found a way yet: Waiting for an answer if it would be possible or not :)

**Comment by MichalJankowskii** [comment]
You will need to wait for an answer a bit. I will not have access to the computer with dev software until mid of Jan. 

A very short one. Right now it is not possible. I will try to think about how to add this feature. But you need to wait a bit. Of course, you are welcome to extend lib.

**Comment by sw-ms-pradipbaria** [comment]
@MichalJankowskii 
Can you suggest way to handle unit test case for the DependentRules  ?

**Comment by MichalJankowskii** [comment]
@sw-ms-pradipbaria are you able to provide a sample of code and the test how you think it should look like for the latest version of lib. And I will try to figure out something.

**Comment by sw-ms-pradipbaria** [comment]
@MichalJankowskii  Please consider below example which has some pre-validtion **BasicValidation()** and DependentRules()
Please note  **BasicValidation()** is `private class`

```c#
RuleFor(m => m).SetValidator(new BasicValidation())
.DependentRules(() => {
RuleFor(m => m.IdOfSthInDb)
   //Complex validation DB validation
    .MustAsync(ItemMustExists)
    .WithMessage("Item does not exist.");
});
```

Can you suggest simplified way to write unit test case for this type of validators, I have tried different approach but they not seems good to me or need lot of work.

Thanks.

**Comment by MichalJankowskii** [comment]
Can you add also the whole class code. Or even compiled into solution. I want to help you but I have limited time.

**Comment by sw-ms-pradipbaria** [comment]
@MichalJankowskii Thanks for willing to help me out on this. 
Please look into below gits, it have full code example. 
[https://gist.github.com/sw-ms-pradipbaria/54b3a448293cb5e5a0207d5b2d6e9c25](https://gist.github.com/sw-ms-pradipbaria/54b3a448293cb5e5a0207d5b2d6e9c25)

Quick view about this sample
- Contains PreValidation private class which will do Business level validation - I know fluentvalidation [PreValidate](https://docs.fluentvalidation.net/en/latest/advanced.html#prevalidate) But we have already developed as per gits using previous version of fluentvalidation.
- And After that I need to perform DB level validation

Thanks!

**Comment by jaumemilian** [comment]
Hi,

Is there finally a way to test the dependant rules?

Thanks,
Jaume
