### ISSUE TITLE
how add test for InlineValidator

### ISSUE THREAD

**Issue by Srivatsa6065** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#17]
Here is my configuration of my Fluent validation 

var workflowListContactMessage = new InlineValidator<WorkflowListContactMessage>();

            workflowListContactMessage.RuleFor(x => x.SequenceNo)
                .GreaterThan(0)
                .WithMessage(MissingInfo);

RuleForEach(x => x.WorkflowListContacts)
                .SetValidator(workflowListContactMessage);

Currently i am adding test to validate if there exits an InlineValidator

AssociateWorkflowListContactCommandValidator.ShouldHaveRules(x => x.WorkflowListContacts,
              BaseVerifiersSetComposer.Build()
                .AddChildValidatorVerifier<InlineValidator<WorkflowListContactMessage>>()
            .Create());

I want to know how do i check if the inline validator has a validation rule for SequenceNo

**Comment by MichalJankowskii** [comment]
Try this code:
`
AssociateWorkflowListContactCommandValidator.ShouldHaveRules(x => x.SequenceNo,
	BaseVerifiersSetComposer.Build()
		.AddComparisonValidatorVerifier<GreaterThanValidator<<EntetHereTypeOf_x>>, int>, <EntetHereTypeOf_x>, int>(0)
		.Create());
`
