### ISSUE TITLE
AddChildValidatorVerifier error

### ISSUE THREAD

**Issue by BenOravetz** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#19]
The AddChildValidatorVerifier generic types doesn't seem to be properly working.  The first generic "T" should be the type of the child validator and the second type "TProperty" should be the type of the child.  Neither values seem to be working right now as I got an error saying that "T" needed to be the type of the parent, not the child validator.  When I set "T" as the type of the parent, I get a different error about that not being a validator type.

I am using a RuleForEach() in this case as the child type is a list of types.

**Comment by MichalJankowskii** [comment]
I will look at that. Can you please send a short example of your code. It will be easier for me to reproduce an error.

**Comment by BenOravetz** [comment]
Sure, here's a code example:

`_validator.ShouldHaveRules(request => request.ChangeRequests, BaseVerifiersSetComposer.Build().AddChildValidatorVerifier<AwardChangeRequestViewModelValidator, AwardChangeRequestViewModel>().Create());`

**Comment by MichalJankowskii** [comment]
Thx. I will look at this.

**Comment by MichalJankowskii** [comment]
I fixed this with the latest release.

Code should look like:
`            this.personValidator.ShouldHaveRules(x => x.Address,
                BaseVerifiersSetComposer.Build()
                    .AddChildValidatorVerifier<AddressValidator, Person, Address>()
                    .Create());`

Example is available here: [PersonValidatorTests_NewApproach_BaseVerifiersSetComposer](https://github.com/MichalJankowskii/FluentValidation.Validators.UnitTestExtension/blob/master/src/FluentValidation.Validators.UnitTestExtension.Examples/Test/PersonValidatorTests_NewApproach_BaseVerifiersSetComposer.cs)

Please let me know if it fixed your issue.

**Comment by BenOravetz** [comment]
I've finally been able to get around to testing this and that works great.  Thank you.
