### ISSUE TITLE
Broken with FluentValidation Version 10.0.0.0

### ISSUE THREAD

**Issue by renanaragao** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#20]
Erro:

System.TypeLoadException : Could not load type 'FluentValidation.Validators.ScalePrecisionValidator' from assembly 'FluentValidation, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7de548da2fbae0f0'.

**Comment by MichalJankowskii** [comment]
Working on it.

**Comment by MichalJankowskii** [comment]
Finally I found some time and updated the lib to support FluentValidation 10.x
