### ISSUE TITLE
Plans to target netstandard2.0?

### ISSUE THREAD

**Issue by zumwald** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#6]
The latest NuGet package can't be used in .NET Core or .NET Standard projects.

**Comment by MichalJankowskii** [comment]
I will add to my todo list. It could be great if you can help if you have some free time.

**Comment by MichalJankowskii** [comment]
It is done. Please update lib to a new version.

**Comment by zumwald** [comment]
awesome!! super fast!
