### ISSUE TITLE
Include testing extensions as part of the main FV project? 

### ISSUE THREAD

**Issue by JeremySkinner** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#7]
As I mentioned on Twitter I thought it might be worth considering incorporating these test extensions in the main FV project. 

This would mean we could provide a unified testing experience rather than having both the current test helpers and your project. 

The downside would be that you’d end up being limited to my release schedule as I release all the FV packages together. 

Either way, I’ll add a section to the testing page on the FV that points users here for more info. 

Let me know what you think.

**Comment by MichalJankowskii** [comment]
Maybe we could start for loosely coupling. I would like to save independence in the beginning.

You could add information about this extension to your documentation. Then I would add information that this approach is recommended by you. And finally, I would like to update icon in nuget repo to be same as yours.

And this would be the beginning. After a while, we could see what is happening and then decide if we should combine both repos.

What do you think about this idea?

**Comment by JeremySkinner** [comment]
That sounds like a good place to start. If you want to throw together some wording I'll put it on my doc site, otherwise I'll try and get to it later in the week.

**Comment by MichalJankowskii** [comment]
I think that you can almost copy/paste from main repo page. And just small adjustment. If not please let me know then I will write a short text about it.

**Comment by MichalJankowskii** [comment]
@JeremySkinner I created a pull request with documentation update.

And I have one more question - can I use the same icon for my testing extension as FV has?

**Comment by JeremySkinner** [comment]
Thanks, I've merged this in with some minor fixes for the markdown and grammar. 

As we're not going to combine the projects at the moment let's not use the same logo to avoid any confusion. We can always change the logo if we decide to combine this at a later time.

**Comment by MichalJankowskii** [comment]
Ok. That is fine for me.
