### ISSUE TITLE
How do you use this to test using 'Must' 

### ISSUE THREAD

**Issue by projecteon** [MichalJankowskii/FluentValidation.Validators.UnitTestExtension#9]
`RuleFor(x => x.Postcode).Must(BeAValidPostcode).WithMessage("Please specify a valid postcode");`

I could test that it runs the PredicateValidator, but it would be good to check if it uses the correct Func as well (in this case BeAValidPostcode).

**Comment by keerthinathganjam** [comment]
validator.ShouldHaveRules(x => x.External,
              BaseVerifiersSetComposer.Build()
                .AddPropertyValidatorVerifier<PredicateValidator>(validator.BeAValidPostcode)
            .Create());
